"""
detection_analysis.py
---------------------
Statistical analysis and visualisation of face detection results.

Reads the JSON detection report generated by batch_pipeline.py and
produces four analysis plots:

  1. Face count distribution     — bar chart per image
  2. Face coverage area          — % of image covered by detected faces
  3. Processing time             — ms per image, with mean line
  4. Detection summary dashboard — four-panel overview

Also computes:
  - Ground truth comparison (expected vs detected face count)
  - Per-image detection accuracy
  - Overall pipeline performance metrics

Inputs : data/detection_results.json   (from batch_pipeline.py)
         data/image_metadata.csv        (ground truth expected counts)
Outputs: results/detection_face_count.png
         results/detection_coverage.png
         results/detection_processing_time.png
         results/detection_dashboard.png

Usage:
    python src/detection_analysis.py
"""

import os
import json
import csv
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

# ── Paths ─────────────────────────────────────────────────────────────────────
SRC_DIR     = os.path.dirname(__file__)
ROOT_DIR    = os.path.join(SRC_DIR, "..")
REPORT_PATH = os.path.join(ROOT_DIR, "data", "detection_results.json")
META_PATH   = os.path.join(ROOT_DIR, "data", "image_metadata.csv")
RESULTS_DIR = os.path.join(ROOT_DIR, "results")

# ── Colours ───────────────────────────────────────────────────────────────────
C_FACE    = "#1A8C4E"
C_COVER   = "#1A6BAD"
C_TIME    = "#D85A30"
C_MATCH   = "#1D9E75"
C_MISS    = "#E24B4A"
C_GRID    = 0.25


# ── Data loading ──────────────────────────────────────────────────────────────

def load_report(path):
    """Load JSON detection report. Handles both old and new format."""
    with open(path) as f:
        data = json.load(f)

    # New format: {batch_statistics, per_image_results}
    if "per_image_results" in data:
        return data["per_image_results"], data.get("batch_statistics", {})
    # Old format: flat dict of filename -> result
    return data, {}


def load_ground_truth(path):
    """Load expected face counts from image_metadata.csv."""
    gt = {}
    if not os.path.exists(path):
        return gt
    with open(path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            gt[row["Filename"]] = int(row["Expected_Faces"])
    return gt


# ── Plot functions ────────────────────────────────────────────────────────────

def plot_face_count(names, counts, expected, output_path):
    """Bar chart: detected vs expected face count per image."""
    x     = np.arange(len(names))
    width = 0.38

    fig, ax = plt.subplots(figsize=(12, 5))

    b1 = ax.bar(x - width/2, counts, width, label="Detected",
                color=C_FACE, edgecolor="white", linewidth=0.8)
    ax.bar_label(b1, fmt="%d", padding=3, fontsize=9, fontweight="bold")

    if expected:
        exp_vals = [expected.get(n, 0) for n in names]
        b2 = ax.bar(x + width/2, exp_vals, width, label="Expected",
                    color=C_COVER, edgecolor="white", linewidth=0.8,
                    alpha=0.75)
        ax.bar_label(b2, fmt="%d", padding=3, fontsize=9)

    ax.set_xticks(x)
    ax.set_xticklabels([n.replace("_annotated","").replace(".jpg","")
                        for n in names], rotation=20, ha="right", fontsize=9)
    ax.set_ylabel("Face Count", fontsize=11)
    ax.set_title(
        "Face Detection Results — Detected vs Expected Count\n"
        "OpenCV Haar Cascade  ·  scaleFactor=1.15  ·  minNeighbors=5",
        fontsize=12, fontweight="bold"
    )
    ax.legend(fontsize=10)
    ax.grid(axis="y", alpha=C_GRID)
    ax.set_facecolor("#FAFAFA")
    plt.tight_layout()
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  Saved: {output_path}")


def plot_coverage(names, coverages, output_path):
    """Horizontal bar chart: face coverage % per image."""
    y = np.arange(len(names))
    clean_names = [n.replace("_annotated","").replace(".jpg","")
                   for n in names]

    fig, ax = plt.subplots(figsize=(10, 5))
    bars = ax.barh(y, [c*100 for c in coverages],
                   color=C_COVER, edgecolor="white", height=0.55)
    ax.bar_label(bars, fmt="%.1f%%", padding=4, fontsize=9, fontweight="bold")

    ax.set_yticks(y)
    ax.set_yticklabels(clean_names, fontsize=10)
    ax.set_xlabel("Face Coverage (% of image area)", fontsize=11)
    ax.set_title(
        "Face Coverage Area per Image\n"
        "Fraction of total image pixels occupied by detected face regions",
        fontsize=12, fontweight="bold"
    )
    ax.grid(axis="x", alpha=C_GRID)
    ax.set_facecolor("#FAFAFA")
    plt.tight_layout()
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  Saved: {output_path}")


def plot_processing_time(names, times, output_path):
    """Bar chart: processing time per image with mean line."""
    x = np.arange(len(names))
    mean_t = np.mean(times)
    clean_names = [n.replace("_annotated","").replace(".jpg","")
                   for n in names]

    fig, ax = plt.subplots(figsize=(12, 5))
    colours = [C_TIME if t > mean_t else "#E8A87C" for t in times]
    bars = ax.bar(x, times, color=colours, edgecolor="white", width=0.55)
    ax.bar_label(bars, fmt="%.0fms", padding=3, fontsize=9, fontweight="bold")

    ax.axhline(mean_t, color="#7F77DD", linewidth=1.8, linestyle="--",
               label=f"Mean: {mean_t:.0f} ms")

    ax.set_xticks(x)
    ax.set_xticklabels(clean_names, rotation=20, ha="right", fontsize=9)
    ax.set_ylabel("Processing Time (ms)", fontsize=11)
    ax.set_title(
        "Detection Processing Time per Image\n"
        "Darker bars exceed mean — correlates with image resolution",
        fontsize=12, fontweight="bold"
    )
    ax.legend(fontsize=10)
    ax.grid(axis="y", alpha=C_GRID)
    ax.set_facecolor("#FAFAFA")
    plt.tight_layout()
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  Saved: {output_path}")


def plot_dashboard(names, counts, coverages, times, expected, output_path):
    """Four-panel detection analysis dashboard."""
    fig = plt.figure(figsize=(16, 10))
    fig.suptitle(
        "Face Detection Analysis Dashboard\n"
        "OpenCV Haar Cascade  ·  Batch of 6 Images  ·  "
        "IIT Hyderabad AI & Deep Learning Workshop",
        fontsize=13, fontweight="bold", y=0.98
    )
    gs = gridspec.GridSpec(2, 2, wspace=0.35, hspace=0.45)

    clean = [n.replace(".jpg","").replace(".jpeg","")
             for n in names]

    # ── Panel 1: Face counts ──────────────────────────────────────────────
    ax1 = fig.add_subplot(gs[0, 0])
    x = np.arange(len(names))
    bars = ax1.bar(x, counts, color=C_FACE, edgecolor="white", width=0.55)
    ax1.bar_label(bars, fmt="%d", padding=3, fontsize=9, fontweight="bold")
    if expected:
        exp_vals = [expected.get(n+".jpg", expected.get(n, 0)) for n in clean]
        ax1.plot(x, exp_vals, "o--", color=C_COVER, linewidth=1.5,
                 markersize=6, label="Expected")
        ax1.legend(fontsize=8)
    ax1.set_xticks(x)
    ax1.set_xticklabels(clean, rotation=25, ha="right", fontsize=7.5)
    ax1.set_ylabel("Face Count", fontsize=10)
    ax1.set_title("Detected Faces per Image", fontsize=11, fontweight="bold")
    ax1.grid(axis="y", alpha=C_GRID)
    ax1.set_facecolor("#FAFAFA")

    # ── Panel 2: Coverage ─────────────────────────────────────────────────
    ax2 = fig.add_subplot(gs[0, 1])
    bars2 = ax2.bar(x, [c*100 for c in coverages],
                    color=C_COVER, edgecolor="white", width=0.55)
    ax2.bar_label(bars2, fmt="%.1f%%", padding=3, fontsize=8.5,
                  fontweight="bold")
    ax2.set_xticks(x)
    ax2.set_xticklabels(clean, rotation=25, ha="right", fontsize=7.5)
    ax2.set_ylabel("Coverage (%)", fontsize=10)
    ax2.set_title("Face Coverage Area", fontsize=11, fontweight="bold")
    ax2.grid(axis="y", alpha=C_GRID)
    ax2.set_facecolor("#FAFAFA")

    # ── Panel 3: Processing time ──────────────────────────────────────────
    ax3 = fig.add_subplot(gs[1, 0])
    colours = [C_TIME if t > np.mean(times) else "#E8A87C" for t in times]
    bars3 = ax3.bar(x, times, color=colours, edgecolor="white", width=0.55)
    ax3.bar_label(bars3, fmt="%.0f", padding=3, fontsize=8.5,
                  fontweight="bold")
    ax3.axhline(np.mean(times), color="#7F77DD", linewidth=1.5,
                linestyle="--", label=f"Mean {np.mean(times):.0f}ms")
    ax3.set_xticks(x)
    ax3.set_xticklabels(clean, rotation=25, ha="right", fontsize=7.5)
    ax3.set_ylabel("Processing Time (ms)", fontsize=10)
    ax3.set_title("Processing Time per Image", fontsize=11, fontweight="bold")
    ax3.legend(fontsize=8)
    ax3.grid(axis="y", alpha=C_GRID)
    ax3.set_facecolor("#FAFAFA")

    # ── Panel 4: Summary metrics ──────────────────────────────────────────
    ax4 = fig.add_subplot(gs[1, 1])
    ax4.axis("off")

    detection_rate = sum(1 for c in counts if c > 0) / len(counts) * 100
    metrics = [
        ("Total images processed",  f"{len(names)}"),
        ("Detection rate",          f"{detection_rate:.1f}%"),
        ("Total faces detected",    f"{sum(counts)}"),
        ("Mean faces per image",    f"{np.mean(counts):.2f}"),
        ("Max faces (one image)",   f"{max(counts)}"),
        ("Mean face coverage",      f"{np.mean(coverages)*100:.1f}%"),
        ("Mean processing time",    f"{np.mean(times):.0f} ms"),
        ("Total processing time",   f"{sum(times):.0f} ms"),
        ("Algorithm",               "Haar Cascade (Viola-Jones)"),
        ("scaleFactor",             "1.15"),
        ("minNeighbors",            "5"),
        ("Preprocessing",           "Histogram equalisation"),
    ]

    for i, (label, value) in enumerate(metrics):
        y_pos = 0.95 - i * 0.077
        ax4.text(0.02, y_pos, label + ":",
                 transform=ax4.transAxes, fontsize=9.5,
                 color="#555555")
        ax4.text(0.62, y_pos, value,
                 transform=ax4.transAxes, fontsize=9.5,
                 fontweight="bold", color="#1A1A1A")

    ax4.set_title("Pipeline Summary", fontsize=11, fontweight="bold")
    ax4.add_patch(plt.Rectangle((0,0),1,1, fill=False,
                                 edgecolor="#CCCCCC", linewidth=1,
                                 transform=ax4.transAxes))

    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  Saved: {output_path}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    os.makedirs(RESULTS_DIR, exist_ok=True)

    results, batch_stats = load_report(REPORT_PATH)
    ground_truth         = load_ground_truth(META_PATH)

    names     = list(results.keys())
    counts    = [results[n]["face_count"]    for n in names]
    coverages = [results[n]["face_coverage"] for n in names]
    times     = [results[n]["processing_ms"] for n in names]

    print("Detection Analysis")
    print(f"\n  Images in report : {len(names)}")

    if batch_stats:
        print(f"  Detection rate   : {batch_stats.get('detection_rate_pct','N/A')}%")
        print(f"  Total faces      : {batch_stats.get('total_faces_detected','N/A')}")
        print(f"  Mean time/image  : {batch_stats.get('mean_processing_ms','N/A')} ms")

    # Ground truth comparison
    if ground_truth:
        print(f"\n  Ground truth comparison:")
        print(f"  {'Image':<35} {'Expected':>9} {'Detected':>9} {'Match':>7}")
        print("  " + "─" * 63)
        correct = 0
        for name in names:
            exp     = ground_truth.get(name, "?")
            det     = results[name]["face_count"]
            match   = "✓" if exp == det else "✗"
            if exp == det: correct += 1
            print(f"  {name:<35} {str(exp):>9} {det:>9} {match:>7}")
        if isinstance(exp, int):
            print(f"\n  Exact match accuracy: {correct}/{len(names)} "
                  f"({correct/len(names)*100:.1f}%)")

    print("\nGenerating plots...")
    plot_face_count(
        names, counts, ground_truth,
        os.path.join(RESULTS_DIR, "detection_face_count.png"))
    plot_coverage(
        names, coverages,
        os.path.join(RESULTS_DIR, "detection_coverage.png"))
    plot_processing_time(
        names, times,
        os.path.join(RESULTS_DIR, "detection_processing_time.png"))
    plot_dashboard(
        names, counts, coverages, times, ground_truth,
        os.path.join(RESULTS_DIR, "detection_dashboard.png"))

    print("\nDetection analysis complete. 4 plots saved to results/")


if __name__ == "__main__":
    main()
